### PR TITLE
Fix shell init --dry-run plus some cleanup

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by wolfv** [comment]
just to make sure – you removed the `reverse` for now?

**Comment by jonashaag** [comment]
yes, can also bring it back, it seemed confusing because it's not implemented anywhere

**Comment by wolfv** [comment]
I think the `reverse` is implemented in the conda shell init which is why I also originally planned for it... Now we have the PR that implements shell deinit in #1781 (which unfortunately will conflict with this PR, I think).

**Comment by jonashaag** [comment]
Yep, happy to rebase when the other one is merged

**Comment by jonashaag** [comment]
This should be good to merge but needs squashing.

**Pull request merged**
