### PR TITLE
try micromamba installation

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by dhirschfeld** [comment]
you could try the shortpath name:
```
C:/PROGRA~1/7-Zip/7z.exe
```

**Comment by dhirschfeld** [comment]
```powershell
> (New-Object -ComObject Scripting.FileSystemObject).GetFolder("C:\Program Files\7-Zip").ShortPath
C:\PROGRA~1\7-Zip
```

**Comment by wolfv** [comment]
thanks @dhirschfeld I just saw that `tar.exe` is also available. Hopefully that works :)

**Comment by dhirschfeld** [comment]
tar and curl are both available on modern windows

**Comment by wolfv** [comment]
hmm seems to stall though ..

**Comment by wolfv** [comment]
thanks dave, your trick actually worked with 7zip! :)

**Pull request closed without merging**
