### PR TITLE
Prevent a memory leak

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/mamba-org/mamba/issues/554

### CODE REVIEW

**Comment by wolfv** [comment]
Thanks!

**Comment by isuruf** [comment]
Thanks @wolfv. Do you have plans for a release soon?

**Comment by wolfv** [comment]
pushed a release. feel free to merge on the micromamba feedstock if you want (I am heading to the bed).

**Comment by isuruf** [comment]
Thanks @wolfv

**Pull request merged**
