### PR TITLE
Fix fish scripts

### PR DESCRIPTION
**Pull request by jonashaag**
Closes https://github.com/mamba-org/mamba/pull/2079
xref https://github.com/mamba-org/mamba/pull/2099

In fish `(subproc)` will replace newlines with spaces. We need `| source` to keep the newlines. This seems to be a bug that I copy-pasted from [upstream](https://github.com/conda/conda/blob/89ba55365be266c11b311bf9bf7f5a21fb1e6ab5/conda/shell/etc/fish/conf.d/conda.fish#L72). I'll send a PR there.

I also refactored the shell init commands to use the environment variables they've just set, to make changing configuration easier.

### CODE REVIEW

**Comment by wolfv** [comment]
Looks good to me! Does this also fix https://github.com/mamba-org/mamba/pull/2079 ?

**Comment by jonashaag** [comment]
Yes

**Comment by jonashaag** [comment]
Cherry-picked it, also https://github.com/mamba-org/mamba/pull/2099

**Review by wolfv — APPROVED** [review]

**Comment by wolfv** [comment]
Thanks for taking care of this!

**Pull request merged**
