### PR TITLE
Implement --use-index-cache for micromamba

### PR DESCRIPTION
**Pull request by dufferzafar**
PR #1762 made this work in mamba.

### CODE REVIEW

**Comment by dufferzafar** [comment]
@AdrianFreundQC I have basic code in place that compiles, but the argument isn't working as-expected yet. Will debug that now.

**Comment by jonashaag** [comment]
@dufferzafar What’s the status here?

**Comment by dufferzafar** [comment]
@jonashaag I never could get this code to work. If you can please review and guide me towards what might be missing, I'd be happy to fix it!

**Comment by jonashaag** [comment]
OK, I'll close this due to inactivity for now.

**Pull request closed without merging**
