### PR TITLE
Revert "Remove created prefix if aborted with `--platform` (#2738)"

### PR DESCRIPTION
**Pull request by Hind-M**
This reverts commit beebd7ee4720e6d972c54c4fd95a7ade821b1af6.

### CODE REVIEW

**Comment by jonashaag** [comment]
I don't think the CI failure is related

**Comment by Hind-M** [comment]
Reverting here is intended to see if the failure persists... We'll see (maybe a bad merge with the previous [commit](https://github.com/mamba-org/mamba/commit/3c3fa084e23270bb3e93ad1616169331d46996f3)?)

**Comment by Hind-M** [comment]
@AntoinePrv maybe we should wait until we see how it goes with #2741?

**Review by JohanMabille — CHANGES_REQUESTED** [review]
We should close this, see my comment in #2741

**Pull request closed without merging**
