### PR TITLE
Pin spdlog

### PR DESCRIPTION
**Pull request by jonashaag**
Temporarily work around broken builds with new spdlog build

### CODE REVIEW

**Comment by jonashaag** [comment]
@AntoinePrv

**Comment by AntoinePrv** [comment]
@jonashaag #2040 Was merged so this should pass if you rebase on `main`.

**Comment by jonashaag** [comment]
Shall we wait for #2048 instead?

**Comment by jonashaag** [comment]
@AntoinePrv i will leave the decision to use this or not to you since you are working on a proper fix I guess?

**Pull request closed without merging**
