### PR TITLE
Fixed libmamba crash when using `pip`

### PR DESCRIPTION
**Pull request by Klaim**
Also added an overload of `env::which` taking a list of search paths for the executable to find.

### CODE REVIEW

**Comment by chaubold** [comment]
I'm sorry that I introduced that crash on Windows with my fix in #1815, but @Klaim your fix actually re-introduces the problem that installing packages with pip in environments with spaces in their path does not work 😞 #1805. 

Now, using `micromamba=0.25.1` the Python executable used for the pip installation process is not found if the path to Python contains a space. At least on Mac. If I use `micromamba=0.25.0` then it works.

**Comment by Klaim** [comment]
@chaubold Ouch, sorry about that, I wasn't aware of that other issue. I'll make a fix so that both issues work.

**Comment by chaubold** [comment]
Yeah, I should have added a test in the first place... Sorry about that. 
If you set up a fix that would be awesome, please ping me in the PR, I'm happy to try it out and help reviewing.

**Comment by Klaim** [comment]
@chaubold https://github.com/mamba-org/mamba/pull/1838 should fix it, also added a test

**Pull request merged**
