### PR TITLE
Allow defaults::* spec

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/mamba-org/mamba/issues/2431

I'm not sure if this is the best way to fix this. Let me know what your thoughts are.

cc @jonashaag @AntoinePrv @jaimergp

### CODE REVIEW

**Comment by jonashaag** [comment]
Thanks!

Looks like it could be correct. We should know with a unit test :)

**Comment by isuruf** [comment]
Added a test. Ready for review again.

**Review by jonashaag — APPROVED** [review]
Not sure if this is the best way to do it but it is definitely an improvement over the current situation.

**Comment by jaimergp** [comment]
Is there any chance you folks would accept a backport for the 1.x branch so we can get this out relatively soon? It would be awesome to have this fix for conda-libmamba-solver!

**Comment by jonashaag** [comment]
IMO definitely yes!

**Comment by JohanMabille** [comment]
@jaimergp yes, waiting for [this one](https://github.com/mamba-org/mamba/pull/2926) to get in too, and then we can start to backport and release.

**Pull request merged**
