### PR TITLE
compatibility fixes for conda 23.9 and conda-libmamba-solver 23.9

### PR DESCRIPTION
**Pull request by jaimergp**
There have been some changes that break `mamba`'s CLI:

- `conda` has deprecated `ensure_name_or_prefix`. We do that manually now.
- `conda` does not take `context` as an argument in `init_loggers` anymore.
- `conda-libmamba-solver` exposes the same `repoquery` subcommand through the subcommand plugin system, which causes a [conflict in Python 3.11](https://github.com/conda/conda-libmamba-solver/issues/303). Interestingly only in that version.

### CODE REVIEW

**Review by JohanMabille — APPROVED** [review]

**Comment by JohanMabille** [comment]
We should probably also add a lower bound to the conda dependency in [environment dev file](https://github.com/mamba-org/mamba/blob/main/mamba/environment-dev.yml)

**Comment by JohanMabille** [comment]
Also we may want to backport this fix to a 1.x branch; with all recent API breaking changes, next release of mamba will be 2.0 and is not planned for soon.

**Comment by JohanMabille** [comment]
Thanks!

**Comment by JohanMabille** [comment]
@jaimergp thanks! Here you go: https://github.com/mamba-org/mamba/tree/1.x

**Comment by jaimergp** [comment]
@JohanMabille 🚀 -> https://github.com/mamba-org/mamba/pull/2890

**Pull request merged**
