### PR TITLE
Finalized Solver bindings and add solver doc

### PR DESCRIPTION
**Pull request by AntoinePrv**

### CODE REVIEW

**Comment by jaimergp** [comment]
Are these docs being published somewhere? I can't find them on readthedocs; only https://mamba.readthedocs.io/en/latest/api/specs.html

cc @AntoinePrv

**Comment by AntoinePrv** [comment]
Not sure how docs get deployed, cc @JohanMabille, any errors on the readthedocs?

**Comment by jaimergp** [comment]
I don't see any errors, but also no recent triggers: https://readthedocs.org/projects/mamba/builds/

**Comment by AntoinePrv** [comment]
@jaimergp  The webhook was dead somehow, it's live now (thanks Johan).
https://mamba.readthedocs.io/en/latest/usage/specs.html

**Comment by jaimergp** [comment]
Wow, https://mamba.readthedocs.io/en/latest/usage/solver.html is sooo good! Thanks for writing that up!

**Pull request merged**
