### PR TITLE
implement mamba remove --force as --no-deps

### LINKED ISSUE #1523: Mamba remove --force different than Conda
(Maybe a duplicate of #1521?)

```
$ mamba create -n test pyarrow
...
```

Mamba:

```
$ mamba remove -n test --dry-run --force arrow-cpp
...

  Removing specs:

   - arrow-cpp
...
  Remove: 60 packages
...
```

Conda:

```
$ conda remove -n test --dry-run --force arrow-cpp
...
The following packages will be REMOVED:

  arrow-cpp-7.0.0-py310hdcb6bdc_2_cpu
...
```

Micromamba: same as Conda

### PR DESCRIPTION
**Pull request by jaimergp**
Closes #1523 

Implements `--force` via `--no-deps`. Output is a bit different but behaviour should be the same (or at least closer to `conda`'s):

```
$ mamba create -n scipy scipy
$ mamba activate scipy
$ mamba remove --force numpy
Removing specs: ['numpy']
Transaction

  Prefix: /opt/conda

  Removing specs:

   - numpy


  Package           Version  Build                     Channel         Size
─────────────────────────────────────────────────────────────────────────────
  Remove:
─────────────────────────────────────────────────────────────────────────────

  - numpy            1.26.0  py310h7f380f4_0           conda-forge         

  Ignored:
─────────────────────────────────────────────────────────────────────────────

  = libblas           3.9.0  17_linuxaarch64_openblas  conda-forge         
  = libcblas          3.9.0  17_linuxaarch64_openblas  conda-forge         
  = libgfortran-ng   13.2.0  he9431aa_0                conda-forge         
  = libgfortran5     13.2.0  h582850c_0                conda-forge         
  = liblapack         3.9.0  17_linuxaarch64_openblas  conda-forge         
  = libopenblas      0.3.23  pthreads_hd703e6f_0       conda-forge         
  = scipy            1.11.2  py310hcbab775_1           conda-forge         

  Summary:

  Remove: 1 packages
  Ignored: 7 packages

  Total download: 0 B

─────────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n]
```

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Thanks!

**Comment by jaimergp** [comment]
@JohanMabille I think this would be a good candidate for the 1.x branch and eventual release, wdyt?

**Comment by JohanMabille** [comment]
@jaimergp sorry for the late response, ttotally agree that this should be backported to 1.x. We need to backport https://github.com/mamba-org/mamba/pull/2897 as well, but depending ont the time it will take we can make an release before.

**Review by JohanMabille — APPROVED** [review]

**Comment by jaimergp** [comment]
I can open the backport tomorrow.

**Pull request merged**
