### PR TITLE
No profile.d fallback in rc files

### PR DESCRIPTION
**Pull request by AntoinePrv**
Continuation to #2631. 

@jonashaag @pavelzw does the error handling seem good to you, or will it be incompatible with #2577?

For readability, current output on my system is:
```bash
# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/home/antoine/workspace/github.com/mamba-org/mamba/build/cmake/micromamba/micromamba';
export MAMBA_ROOT_PREFIX='/home/antoine/.local/share/mamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba='echo "Failed to initialize shell for micromamba.\nTry running micromamba shell reinit." 1>&2; "$MAMBA_EXE" "$@"'
fi
unset __mamba_setup
# <<< mamba initialize <<<
```

### CODE REVIEW

**Comment by jonashaag** [comment]
Does this even work? If you set `micromamba` to this dummy function, how are you supposed to `shell reinit`?

**Comment by AntoinePrv** [comment]
It would because the message is added at the top, then the alias calls into `$MAMBA_EXE`.
But you make me realize that perhaps we could simply fallback to `alias micromamba="$MAMBA_EXE`, since activating with the binary will give the message:
```txt
'micromamba' is running as a subprocess and can't modify the parent shell.
Thus you must initialize your shell before using activate and deactivate.

To initialize the current  shell, run:
    $ eval "$(micromamba shell hook --shell )"
and then activate or deactivate with:
    $ micromamba activate
To automatically initialize all future () shells, run:
    $ micromamba shell init --shell  --root-prefix=~/micromamba

Supported shells are {bash, zsh, csh, xonsh, cmd.exe, powershell, fish}.
```

**Comment by jonashaag** [comment]
Oh sorry I didn't see the call into `$MAMBA_EXE` 🙈 I would actually prefer to see error messages. Maybe we can remove the `2>/dev/null` above?

**Review by jonashaag — APPROVED** [review]

**Comment by AntoinePrv** [comment]
> Somewhat relatedly, I would actually prefer to see error messages. Maybe we can remove the 2>/dev/null above?

That's a good idea! I think we should delay it unit the user calls `micromamba` and not when the rc file is sourced.

**Comment by AntoinePrv** [comment]
I propose:
```bash
# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/home/antoine/workspace/github.com/mamba-org/mamba/build/cmake/micromamba/micromamba';
export MAMBA_ROOT_PREFIX='/home/antoine/workspace/github.com/mamba-org/mamba/foo';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<
```
And the message
```
'micromamba' is running as a subprocess and can't modify the parent shell.
Thus you must initialize your shell before using activate and deactivate.

To initialize the current  shell, run:
    $ eval "$(micromamba shell hook --shell )"
and then activate or deactivate with:
    $ micromamba activate
To automatically initialize all future (zsh) shells, run:
    $ micromamba shell init --shell zsh --root-prefix=~/micromamba
If your shell was already initialized, reinitialize your shell with:
    $ micromamba shell reinit --shell
Otherwise, this may be an issue. In the meantime you can run commands. See:
    $ micromamba run --help

Supported shells are {bash, zsh, csh, xonsh, cmd.exe, powershell, fish}.
```

**Review by JohanMabille — APPROVED** [review]

**Pull request merged**
