### PR TITLE
Incremental ccache updates + Cache Conda env

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by jonashaag** [comment]
@wolfv this is pretty slick, ~ 1 minute per CI job (except Windows). It needs https://github.com/mamba-org/provision-with-micromamba/pull/36 because it has to create an empty Micromamba install so that we can cache the `envs/` directory only. As an alternative we could also implement caching directly in the `provision-with-micromamba` action?

Also I don't understand this test failure:

```
Run micromamba activate build_env
  micromamba activate build_env
  mamba create -n test_env xtensor -c conda-forge -y
  mamba env create -f mamba/tests/test_env.yml
  mamba env update -f mamba/tests/update_env.yml
  shell: /usr/bin/bash -l {0}
  env:
    MAMBA_ROOT_PREFIX: /home/runner/micromamba
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba

Transaction
  Prefix: /home/runner/micromamba/envs/build_env/envs/test_env
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ WTF?
```

**Comment by wolfv** [comment]
I am wondering if we should give `sscache` a try ... https://github.com/mozilla/sccache It's supposed to work with MSVC as well. There is also a package on conda-forge.

**Comment by jonashaag** [comment]
Will have a look!

**Comment by wolfv** [comment]
I foudn it in this action: https://github.com/lief-project/LIEF/blob/5d50528c71984da8c91ab651a8efb5f58f778039/.github/workflows/windows.yml#L46

**Comment by jonashaag** [comment]
Closing this, will use env caching from micromamba action

**Pull request closed without merging**
