### PR TITLE
Fixed crash when installing from env file with pip section (fix #1975)

### LINKED ISSUE #1975: filesystem error: cannot make absolute path with 0.26
Hello;

Our package doesn't build anymore using Mamba, although it has always been in the past. It might be related to the new 0.26 version.

Details https://app.travis-ci.com/github/radis/radis/jobs/584458524#L310

```
info     libmamba ****************** Backtrace Start ******************
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
trace    libmamba Compute configurable 'root_prefix'
trace    libmamba Get RC files configuration from locations up to HomeDir
trace    libmamba Configuration not found at '/home/travis/.mambarc'
trace    libmamba Configuration not found at '/home/travis/.condarc'
trace    libmamba Configuration not found at '/home/travis/.conda/condarc.d'
trace    libmamba Configuration not found at '/home/travis/.conda/condarc'
trace    libmamba Configuration not found at '/home/travis/.conda/.condarc'
trace    libmamba Configuration not found at '/home/travis/micromamba/.mambarc'
trace    libmamba Configuration not found at '/home/travis/micromamba/condarc.d'
trace    libmamba Configuration not found at '/home/travis/micromamba/condarc'
trace    libmamba Configuration not found at '/home/travis/micromamba/.condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.mambarc'
trace    libmamba Configuration not found at '/var/lib/conda/condarc.d/'
trace    libmamba Configuration not found at '/var/lib/conda/condarc'
trace    libmamba Configuration not found at '/var/lib/conda/.condarc'
trace    libmamba Configuration not found at '/etc/conda/.mambarc'
trace    libmamba Configuration not found at '/etc/conda/condarc.d/'
trace    libmamba Configuration not found at '/etc/conda/condarc'
trace    libmamba Configuration not found at '/etc/conda/.condarc'
trace    libmamba Update configurable 'no_env'
trace    libmamba Compute configurable 'file_specs'
critical libmamba filesystem error: cannot make absolute path: Invalid argument []
```

I do not understand what's wrong from the error message.  What informations do you need to debug ?

### PR DESCRIPTION
**Pull request by Klaim**
This should fix #1975

### CODE REVIEW

**Comment by jonashaag** [comment]
We should add a test :)

**Comment by Klaim** [comment]
> We should add a test :)

Ah yes good point

**Comment by Klaim** [comment]
The test fails for me before the fix commit.

**Comment by wolfv** [comment]
Awesome, thanks @Klaim !

**Pull request merged**
