### PR TITLE
make mamba support "mamba update --all one_package==x.x.x" like conda

### PR DESCRIPTION
**Pull request by zhangfeiran**
This is useful to update all packages while excluding one (several) specific package(s).

### CODE REVIEW

**Comment by jjerphan** [comment]
Hello,

Unfortunately the code-base of mamba has drastically changed since `1.x` and this PR is not applicable anymore. Also I do not think we want to support all the features of conda.

**Comment by Hoeze** [comment]
> Also I do not think we want to support all the features of conda.

@jjerphan While I agree in general, this specific feature is quite annoying not to have.

**Comment by zhangfeiran** [comment]
I'm actually ok without this feature now, since adding package to `myenv/conda-meta/pinned` file is a more persistent way.

**Comment by jjerphan** [comment]
I invite you to continue the discussions on this issue https://github.com/mamba-org/mamba/issues/1231, specifying your needs.

**Pull request closed without merging**
