### PR TITLE
Test stubs

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by dholth** [comment]
I would do this with the black formatter and a text compare

**Comment by wolfv** [comment]
We have the formatters only in the pre-commit environment so I chose this route as we need fewer dependencies.

**Comment by AntoinePrv** [comment]
That could be a cool pre-commit hook to generate the stubs!

**Comment by wolfv** [comment]
Indeed, but you do need the compiled `libmambapy.bindings` file for that...

**Pull request merged**
