### PR TITLE
feat(fs): Replace 'last_write_time' by underlying 'utimesat' to suppo…

### PR DESCRIPTION
**Pull request by FeatCrush**
#1123

### CODE REVIEW

**Comment by wolfv** [comment]
Thanks for investigating this and proposing this fix. I am doubtful that this works on Windows. Also I think I'd prefer to wrap this in a function, and maybe only use it on Linux.

**Comment by FeatCrush** [comment]
Hello @wolfv  i'll try to take some time to work on the issue

**Comment by wolfv** [comment]
Ping @FeatCrush are you on this?

**Comment by adriendelsalle** [comment]
@wolfv I'm not sure any change is required, please see https://github.com/mamba-org/mamba/issues/1123#issuecomment-959739126

**Pull request closed without merging**
