### PR TITLE
Fix #1751: Better error message if root prefix is not a directory

### LINKED ISSUE #1751: micromamba crashes when launched from home folder
To reproduce, execute
```
sudo docker run -it --rm ubuntu:latest bash
apt update ; apt install -y curl bzip2
cd ; curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba ; cp -r bin/micromamba ~
./micromamba; echo $?
```
and observe that the exit code 1 is printed instead of the micromamba info page followed by exit code 0

I observed this behavior on Ubuntu 22.04 and CentOS 7.

If micromamba is placed in home folder, other copies of the executable placed in other location will crash as well.

### PR DESCRIPTION
**Pull request by jonashaag**
Fixes https://github.com/mamba-org/mamba/issues/1751

@adriendelsalle it seems like these lines cause the error messages I improved not to be shown. Is it on purpose that only critical errors are printed in this case? https://github.com/mamba-org/mamba/blob/f2ac46b1c478668ed09463cf5b88d4802af7661b/libmamba/src/api/configuration.cpp#L1636-L1637

### CODE REVIEW

**Comment by adriendelsalle** [comment]
Hi @jonashaag the configuration computation starts before knowing the log level from rc file, cli flag or env var so I disabled the logger to avoid printing some logs from configurables that are loaded before the log level.
We use the backtrace to replay logs if some errors are thrown.
Since this I also implemented a log buffer needed for the progress bars display (to flush the log messages and regular prints at the right time when updating the status, between deleting the N previous lines and writing the new ones)

**Comment by adriendelsalle** [comment]
The logs are printed at the end of the same function https://github.com/mamba-org/mamba/blob/f2ac46b1c478668ed09463cf5b88d4802af7661b/libmamba/src/api/configuration.cpp#L1668

**Comment by jonashaag** [comment]
Thanks, but then we have stuff like this that makes the logs never show up https://github.com/mamba-org/mamba/blob/57668935ce5697616d8bc1d2e1b6b0da6589a0c5/libmamba/src/api/configuration.cpp#L542

**Comment by adriendelsalle** [comment]
Indeed, it's also bad to use `exit` for bindings because it would cause `R` or `Python` interpreters to exit from interactive mode.
Could you try to throw an error instead?

@wolfv we discussed a long time ago to refactor the code base to replace those statements this way, right?

**Comment by jonashaag** [comment]
Changed most `exit()` calls to C++ exception.

**Comment by wolfv** [comment]
Thanks! Nice improvement

**Pull request merged**
