### PR TITLE
fix: only reactivate current environment

### PR DESCRIPTION
**Pull request by chawyehsu**
Fixes: #2724

### CODE REVIEW

**Comment by jonashaag** [comment]
Thank you for working on this. Why is this necessary for Powershell but not the other shells?

**Comment by chawyehsu** [comment]
Theoretically, if it's not the current environment, then don't reactivate is the proper behavior for all shells. But it seems all other shells except for powershell can trigger reactivation and ignore the error of no-op silently. The check of matching current environment can be added to all other shells but I doubt the necessity.

**Review by jonashaag — CHANGES_REQUESTED** [review]
We should instead change the C++ code that handles `shell reactivate -s powershell` to return a noop that doesn't cause an error in Powershell

**Comment by jonashaag** [comment]
> The check of matching current environment can be added to all other shells

Alternatively, we can do this for all shells. But it's confusing to have this implemented for a single shell only

**Comment by chawyehsu** [comment]
> We should instead change the C++ code that handles shell reactivate -s powershell to return a noop that doesn't cause an error in Powershell.

In fact the c++ code already did the right part, returning empty for shells. The problem is on the powershell side, powershell throws error trying to execute the noop empty script block, and that's reason it needs the patch.

Another way to fix this it what [dhirschfeld](https://github.com/dhirschfeld) commented in https://github.com/mamba-org/mamba/issues/2724#issuecomment-1663081812, which is simpler (just ignore the return) but less semantic context.

**Comment by jonashaag** [comment]
Can't we make the C++ code output something that's a noop but syntactically correct?

**Comment by chawyehsu** [comment]
Maybe. But what's the consideration of specializing the output from C++ for one shell, which from another point of view can also be a confusion? Fixing the issue on the shell side for the shell is the simplest and safe way I could propose.

**Comment by jonashaag** [comment]
I consider it a bug in the Powershell C++ implementation. The interface is something along the lines of: "Given an environment, `reactivate` outputs a script that can be run in the shell to refresh the shell." Right now the Powershell code doesn't implement this interface correctly, while other shells do.

**Comment by chawyehsu** [comment]
> "Given an environment, reactivate outputs a script that can be run in the shell to refresh the shell."

I see you point, but let me illustrate the current behavoir. The abstract `reactivate` C++ interface returns empty when there is no activating environment, this is correct since you won't need to reactivate when you don't have one env activated.

https://github.com/mamba-org/mamba/blob/6e4d91e2eca3fd913ebf5e91f86c58749f0be179/libmamba/src/core/activation.cpp#L369-L373

The returned `EnvironmentTransform` then is wrapped by [`script()`](https://github.com/mamba-org/mamba/blob/6e4d91e2eca3fd913ebf5e91f86c58749f0be179/libmamba/src/core/activation.cpp#L668), which is a shell-specific function to turn `envt` into shell script. The one of PowerShell:

https://github.com/mamba-org/mamba/blob/6e4d91e2eca3fd913ebf5e91f86c58749f0be179/libmamba/src/core/activation.cpp#L1045-L1080

Nothing special for the PowerShell C++ implementaion, it will return nothing when the `EnvironmentTransform` argument is empty, like `script()` of other shells.

Shells like bash [`eval`](https://github.com/mamba-org/mamba/blob/main/libmamba/data/micromamba.sh#L21) the empty script without issue. However, mamba's PowerShell hook is using the [`Invoke-Expression -Command`](https://github.com/mamba-org/mamba/blob/main/libmamba/data/Mamba.psm1#L120) which can not process empty script silently, `Invoke-Expression` requries a non-empty script block, and this is #2724.

Hence, either you fix it by ignoring the empty return (the shell isde), or returning a non-empty script even if it's a no-op (the C++ side). But what non-empty script should be returned when you want to fix it on the C++ side...

**Comment by jonashaag** [comment]
Thanks for the detailed analysis. I'm fine with keeping the C++ as is. Would you mind reducing your PR to only the non empty check? We can do the other check in another PR that updates all shells.

**Review by jonashaag — APPROVED** [review]

**Comment by jonashaag** [comment]
Thank you!

**Comment by AntoinePrv** [comment]
@jonashaag Can you please stop merging PR when the CI is not green.

**Pull request merged**
