### PR TITLE
fixes for building micromamba and libmambapy

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by AntoinePrv** [comment]
@wolfv , what needs to be updated?

**Comment by wolfv** [comment]
https://github.com/mamba-org/mamba/blob/679c13b232a33c5f2c7f6a62b9de22fae921ae89/.github/workflows/static_build.yml#L34

**Comment by wolfv** [comment]
@AntoinePrv the latest release has some different patches (that are also conflicting with the changes in this PR). I was assuming you hadn't updated your feedstock sources yet?

But yeah, we should probably move it to mamba-org as long as the conda-forge one and our builds here conflict.

**Comment by AntoinePrv** [comment]
I rebased it, but why not merge those changes in the feedstock?

**Comment by AntoinePrv** [comment]
@wolf try to add this commit ce9d1cb6f1a708f5cf9206b9ecc57c170e839b4f

**Comment by wolfv** [comment]
closing in favor of #2216

**Pull request closed without merging**
