### PR TITLE
Extract in subprocess only with concurrency > 1

### PR DESCRIPTION
**Pull request by jonashaag**
cc @maresb

### CODE REVIEW

**Comment by maresb** [comment]
If I am reading this correctly, the change is:

Before: When extracting, spawn `extract_threads` subprocesses for extracting.

After: When extracting, spawn `extract_threads` subprocesses for extracting, unless `extract_threads=1` in which case use the main process.

I just checked the status of [my experiments](https://github.com/jonashaag/docker-stacks/pull/1#issuecomment-1092571485) and the runs went as expected. I did however notice one unexpected detail in [run #105](https://github.com/maresb/docker-stacks/runs/5881499257?check_suite_focus=true) which is hanging after

```
 #36 43.88 info     libmamba Transfer finalized, status 200 [https://conda.anaconda.org/conda-forge/linux-aarch64/python-3.9.12-h2eada40_1_cpython.tar.bz2] 13382366 bytes
#36 43.88 info     libmamba Download finished, validating '/opt/conda/pkgs/python-3.9.12-h2eada40_1_cpython.tar.bz2'
```

Do we need to implement the same logic for `download_threads`?

**Comment by maresb** [comment]
# References
(in chronological order)

* Mamba [sporadically hangs](https://github.com/jupyter/docker-stacks/issues/1539) when building jupyter/docker-stacks arm64 image
* Original [PR](https://github.com/jupyter/docker-stacks/pull/1594) in jupyter/docker-stacks to replace MiniForge with Micromamba.
* Partially [understood/isolated](https://github.com/jupyter/docker-stacks/pull/1594#issuecomment-1087895999) the problem
* [Bug report](https://github.com/mamba-org/mamba/issues/1611) to mamba-org/mamba
* @jonashaag [patches my jupyter/docker-stacks PR](https://github.com/jonashaag/docker-stacks/pull/1) to disable concurrency, and I confirm that it appears to work
* This

**Comment by jonashaag** [comment]
> Do we need to implement the same logic for `download_threads`?

I don't think so; parallel downloading has been there for much longer than parallel extraction and it doesn't seem to cause trouble for you (v0.17).

**Comment by maresb** [comment]
It's not like the logs would stop, only the micromamba logs. So either GH is doing some sort of really clever filtering or the log limit is in micromamba itself.

**Comment by wolfv** [comment]
Thanks both for the thorough debugging of this!
I would love to understand the root cause. Are you using emulation for aarch64? E.g. I think buildx does some form of emulation?
Could it be a memory problem? (e.g. parallel extraction using up all available memory?)

**Comment by maresb** [comment]
Hi @wolfv! Apparently `buildx` uses `QEMU`. It would be interesting to try and reproduce this locally. I have not yet tried, since it's just in the last few days that I started to understand the nature of the problem.

I can't exclude it being a memory problem, but it seems unlikely to me because before @jonashaag's patch I tried `extract_threads=1` and it didn't help. (I wouldn't expect one thread to require significantly more memory, but maybe I'm wrong for some reason.)

**Comment by maresb** [comment]
> parallel downloading has been there for much longer than parallel extraction and it doesn't seem to cause trouble for you (v0.17)

I'm not sure what to make of [this log](https://pipelines.actions.githubusercontent.com/serviceHosts/ee2723ef-0d2c-4021-a502-75bbd74b9474/_apis/pipelines/1/runs/96/signedlogcontent/2?urlExpires=2022-04-08T20%3A53%3A40.1651231Z&urlSigningMethod=HMACV1&urlSignature=XkZrd%2BCWrFMgo8Ljotdu48pHoyC34FYtVZZr2m6bi30%3D). It certainly doesn't cause trouble to the same level as parallel extraction, but I wonder if it could still be occasionally (although rarely) causing trouble.

**Comment by maresb** [comment]
I managed to reproduce locally by cloning maresb/docker-stacks, checking out the `micromamba` branch, and running

```bash
cd base-notebook; docker buildx build . --platform "linux/arm64" --no-cache 
```

For preparatory steps to configure qemu with buildx, see [this comment](https://github.com/jupyter/docker-stacks/pull/1594#issuecomment-1028316739).

**Comment by jonashaag** [comment]
Wow that’s great, will do some debugging later!

Do you have debug logs that you can share in the meantime?

**Comment by jonashaag** [comment]
Also shall we move discussion to a different ticket?

**Comment by maresb** [comment]
> Also shall we move discussion to a different ticket?

Yes, let's end discussion here and continue [there](https://github.com/mamba-org/mamba/issues/1611).

# END

**Pull request merged**
