### PR TITLE
Improve micromamba installation documentation

### PR DESCRIPTION
**Pull request by pavelzw**

### CODE REVIEW

**Comment by wolfv** [comment]
Thanks. There is also another (currently undocumented) way of installing micromamba.

`curl micro.mamba.pm/install.sh | bash` works on macOS and Linux :)

**Comment by pavelzw** [comment]
Since `zsh` is the default shell on macOS I would suggest writing two separate installation commands, one for linux with `bash` and one for macOS with `zsh`.

**Comment by wolfv** [comment]
that should also work!

**Comment by jonashaag** [comment]
We already have instructions in the README and in the Gist linked there. Let’s deduplicate them somehow. 

Btw @yyyasin19 is working a Homebrew recipe for Micromamaba.

**Comment by pavelzw** [comment]
Also, the download instructions for macOS in the Readme are wrong. The linux executable doesn't work on macOS... I now tried to deduplicate as much as possible and just redirect to the official documentation in the readme...

**Review by jonashaag — APPROVED** [review]

**Comment by pavelzw** [comment]
If we want to deduplicate the installation guides, @wolfv should probably reference the official documentation in his [Gist](https://gist.github.com/wolfv/fe1ea521979973ab1d016d95a589dcde) (and maybe remove the installation instructions there completely?).

**Pull request merged**
