### PR TITLE
Fix #2248

### LINKED ISSUE #2248: conda 23.1.0 breaks mamba init
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

No results for "no_user"

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not reproducible with Conda

### Describe your issue

`conda` release 23.1.0 last week includes https://github.com/conda/conda/pull/11949 which removes `no_user` from args. This causes `mamba init` (on 0.25.0, then 1.2.0 after upgrade) to throw an attribute error:

```
'Namespace' object has no attribute 'no_user'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 935, in exception_converter
        raise e
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 928, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 886, in _wrapped_main
        result = do_call(args, p)
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 758, in do_call
        exit_code = shell_init(args)
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba_shell_init.py", line 75, in shell_init
        if args.no_user:
    AttributeError: 'Namespace' object has no attribute 'no_user'
```

Specifically in that PR this change eliminates `no_user` and only keeps `user`:
image

From a glance at `mamba_shell_init.py` (https://github.com/mamba-org/mamba/blob/main/mamba/mamba/mamba_shell_init.py#L84) it looks like `mamba` could pull this block of changes in to resolve this. 

image

### mamba info / micromamba info

```shell
active environment : base
    active env location : /home/davidwagner/anaconda3
            shell level : 5
       user config file : /home/davidwagner/.condarc
 populated config files : /home/davidwagner/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/davidwagner/anaconda3  (writable)
      conda av data dir : /home/davidwagner/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/davidwagner/anaconda3/pkgs
                          /home/davidwagner/.conda/pkgs
       envs directories : /home/davidwagner/anaconda3/envs
                          /home/davidwagner/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.12 Linux/5.15.0-1027-gcp ubuntu/22.04.1 glibc/2.35
                UID:GID : 1009:1010
             netrc file : None
           offline mode : False
```

### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

_No response_

### PR DESCRIPTION
**Pull request by jonashaag**
Closes #2248

### CODE REVIEW

**Comment by jonashaag** [comment]
Hm this is bad the test is supposed to fail

**Comment by wolfv** [comment]
I think the conda version wasn't released on conda-forge yet, because of a conda-build bug.

**Comment by jonashaag** [comment]
Ah, I looked at the wrong place! https://github.com/jonashaag/mamba/actions/runs/4010134326/jobs/6886285496

**Comment by jonashaag** [comment]
OK, fixed: https://github.com/jonashaag/mamba/actions/runs/4013854780

**Comment by jonashaag** [comment]
Please squash merge

**Comment by jonashaag** [comment]
Hmm not sure what's going on

**Comment by jezdez** [comment]
> I think the conda version wasn't released on conda-forge yet, because of a conda-build bug.

Yeah, this is ongoing

**Comment by jonashaag** [comment]
That's good because we haven't fixed compatibility yet! :-D

**Comment by jonashaag** [comment]
Isn’t the last commit just another way to write exactly the same thing?

**Comment by wolfv** [comment]
OK, I think I finally understand what's going on ... running `mamba shell init` probably overwrites what is written by `micromamba` in these files (e.g. stuff between `# <<<<< mamba init <<<<`). ugh. We should have used different delimiters from the start, too bad.

**Comment by jonashaag** [comment]
Another approach would’ve been to set $HOME to a temporary directory for the test.

**Comment by wolfv** [comment]
yes, that's true and is also something we do in the micromamba tests. I'd be fine with merging and releasing this though :)

**Review by wolfv — APPROVED** [review]

**Pull request merged**
