### PR TITLE
[RFC] Add support for UNC file:// urls

### PR DESCRIPTION
**Pull request by adament**
Conda and mamba convert `file:////hostname/share` UNC urls to `file://hostname/share` when reading them from e.g. condarc, in conda they are then converted back to UNC urls in the function `url_to_path` which is used by the `LocalFSAdapter`. Implement a similar hack for mamba as discussed in #733.

Note: I have not been able to get the test suite building on my machine, so I have not run the test suite against this change.

### CODE REVIEW

**Comment by wolfv** [comment]
Can you either add some tests or post some expected values from this function here?
I think for proper testing it might be easier to factor this function out into a standalone function. 

Is this only relevant on Windows?

Is this going to convert `file:///blabla` to `file:////blabla`? Did you check that regular file URL's still work fine?

Besides, this is looking really good! I just don't have a good understanding of UNC urls yet, and in what condition you need to transform them back.

**Comment by adament** [comment]
Good idea splitting it into a separate function, and yes I will add some tests. Do you have any preferences for where to place the function?

As I read the curl manpage it is only relevant for Windows:
```
FILE

Read or write local files. curl does not support accessing file:// URL remotely, but when running on Microsoft Windows using the native UNC approach will work.
```

It should leave `file:///absolute/path` alone and only modify `file://host/share` but some tests would be good to support this. Furthermore it leaves `file://localhost/absolute/path` alone for localhost, 127.0.0.1, and ::1 as this is what conda does, but I have not tested that curl actually supports localhsot file urls.

**Comment by wolfv** [comment]
I think this function can go in a similar place as `fix_win_path`. 
Tests can go into the C++ tests we have in the test subdir.

Thanks for tackling this!

**Comment by wolfv** [comment]
@adament do you think you'll find the time to finish this?

**Comment by adament** [comment]
Yes I hope to get back to it at the end of this week. But if somebody else has time and interest in picking it up they are very welcome.

**Comment by adament** [comment]
@wolfv I have tried adding tests but I have not managed to build the tests on my machine and I cannot quite tell if the CI jobs run the C++ tests?

**Comment by wolfv** [comment]
Yes, the CI should run them! Thanks. I'll check it out tomorrow or Monday

**Comment by wolfv** [comment]
Thanks @adament !

**Comment by wolfv** [comment]
You can find the result of the CI run of these tests here: https://github.com/mamba-org/mamba/pull/749/checks?check_run_id=2149502434#step:6:313

Looks good!

**Pull request merged**
