### PR TITLE
[1.x] Fix x86_64 to use underscore instead of dash

### PR DESCRIPTION
**Pull request by traversaro**
See https://github.com/mamba-org/mamba/issues/3222#issuecomment-2284324975 .

Fix https://github.com/mamba-org/mamba/issues/3222 .

### CODE REVIEW

**Review by isuruf — APPROVED** [review]

**Comment by JohanMabille** [comment]
Thanks for tackling this. Can you rebase on latest 1.x? This should fix the CI.

**Comment by traversaro** [comment]
> Thanks for tackling this. Can you rebase on latest 1.x? This should fix the CI.

Done!

**Review by Hind-M — APPROVED** [review]

**Comment by traversaro** [comment]
Great, thanks! How does it work for forward porting this to `main`/2.* ?

**Comment by Hind-M** [comment]
> Great, thanks! How does it work for forward porting this to `main`/2.* ?

You can open PR against `main` to do the same :) (and mention that it's forward porting this PR).

**Comment by traversaro** [comment]
> > Great, thanks! How does it work for forward porting this to `main`/2.* ?
> 
> You can open a PR against `main` to do the same :) (and mention that it's forward porting this PR).

Great, that is easy. : )

Done in https://github.com/mamba-org/mamba/pull/3433 .

**Comment by matthewfeickert** [comment]
:wave: @JohanMabille @Hind-M Would it be possible to get a `v1.5.10` patch release in the next week with this fix in it? This would unblock all the x86 microarch level packages on conda-forge, which currently can't be installed with `mamba` or `micromamba` (c.f. https://github.com/conda-forge/microarch-level-feedstock/issues/10). I appreciate though that this might not be something that's in the immediate roadmap. Thank you for maintaining this infrastructure for everyone!

**Comment by Hind-M** [comment]
Hey @matthewfeickert, `1.5.10` is available now!

**Comment by matthewfeickert** [comment]
Amazing. Thank you very much @Hind-M (as well as @traversaro for the fix)! :rocket:

**Pull request merged**
