### PR TITLE
Remove banner

### PR DESCRIPTION
**Pull request by jonashaag**
I know this is a controversial proposal :-)

Related issues (some we have fixed already)

- https://github.com/mamba-org/mamba/issues/2189
- https://github.com/mamba-org/mamba/issues/1973
- https://github.com/mamba-org/mamba/issues/984
- https://github.com/mamba-org/mamba/issues/587
- https://github.com/mamba-org/mamba/issues/2089
- https://github.com/mamba-org/mamba/issues/1397
- https://github.com/mamba-org/mamba/issues/1156
- https://github.com/mamba-org/mamba/issues/514
- https://github.com/mamba-org/mamba/issues/2255

### CODE REVIEW

**Comment by JohanMabille** [comment]
Shouldn't we fix the remaining bugs to guarantee that users can remove the banner if they want? Or even have it not displayed by default, but not entirely removed?

**Comment by jonashaag** [comment]
My take is that most users don't want the banner. Why would you want a banner?

**Comment by jonashaag** [comment]
@JohanMabille @AntoinePrv @Klaim @wolfv shall we remove the banners?

**Comment by AntoinePrv** [comment]
I have no objection to removing the banner. I'm already removing it in my `condarc`.

**Comment by Klaim** [comment]
I have no objection either.

**Comment by jonashaag** [comment]
Hi all, I'm going to merge this this week if I don't hear any further feedback :)

**Comment by AntoinePrv** [comment]
How about making the final call tomorrow (Tuesday June 20th 2023) during the mamba meeting?

**Comment by jonashaag** [comment]
I can't join tomorrow but feel free to make a decision :)

**Comment by JohanMabille** [comment]
Sorry for the late reply, I have no objection to removing the banner.

**Review by JohanMabille — APPROVED** [review]

**Comment by corneliusroemer** [comment]
@jonashaag Just for clarification: Does this PR mean there's no more banner in any shape or form in neither mamba nor micromamba from 1.4.5 onwards? 🙏 

I just spent 10 minutes figuring out how to remove the banner after switching to micromamba where my previous environment file solution didn't work anymore.

**Comment by jonashaag** [comment]
Yes!

**Pull request merged**
