### PR TITLE
Install pip deps from lockfile

### LINKED ISSUE #1900: Micromamba ignores pip dependencies from new lockfiles
The new lockfile format allows for the installation of PyPI packages corresponding to the `- pip [...]` section of `environment.yml`. However, it seems that this is not yet supported by micromamba.

To reproduce, create `environment.yml`:

```yaml
name: test-pip-deps
channels:
- conda-forge
dependencies:
- pip
- pip:
  - cowsay
platforms:
- linux-64
```

and generate a new-style lockfile `conda-lock.yml` by running

```bash
conda-lock
```

Create an environment via `conda-lock`, and it works:
```bash
conda-lock install --name conda-lock-pip-deps conda-lock.yml
micromamba activate conda-lock-pip-deps
cowsay moo
micromamba deactivate
```

Try with `micromamba`, and it doesn't work:
```bash
micromamba create --yes --name micromamba-pip-deps --file conda-lock.yml
micromamba activate micromamba-pip-deps
cowsay moo
micromamba deactivate
```

### PR DESCRIPTION
**Pull request by jvansanten**
This piggybacks on the existing `install_for_other_pkgmgr()` that was already used to install pip deps from standard environment specs, and uses the same mechanism as `conda-lock` (synthesizing a requirements.txt with explicit urls and hashes that is then installed with `pip install --no-deps` to prevent `pip` from second-guessing the locked solution).

The implementation is somewhat ugly in that it shoehorns package extraction into `create_explicit_transaction_from_lockfile()`, which needs to fill extracted packages into a non-const vector passed as an argument rather than returning e.g. a tuple, since `MTransaction` lacks a move ctor. I also could not immediately find unit tests that cover `install_for_other_pkgmgr()`, so did not add any new ones for the new case.

Fixes #1900.

### CODE REVIEW

**Comment by maresb** [comment]
Ah, no way!!! I wasn't expecting this, so just now I threw together a Python-based solution [here](https://github.com/maresb/micromamba-install-locked-pip-dependencies), just because I'm not proficient in C. But of course this is much better!

**Comment by wolfv** [comment]
Looks great to me! Thank you!

**Comment by wolfv** [comment]
Looks like there is a failing test. Do you have time to look into that @jvansanten?

**Comment by jvansanten** [comment]
Seems I've finally fumbled my way to passing CI. Can this be merged now?

**Comment by jvansanten** [comment]
Seems I've finally managed to fumble my way to passing CI. Can this be merged now?

**Comment by jonashaag** [comment]
> Looks great to me!

I'll go ahead and merge this, assuming that this was meant to be a PR approval :)

**Comment by wolfv** [comment]
Thanks!

**Pull request merged**
