### PR TITLE
fix: Only register channels in the context once

### PR DESCRIPTION
**Pull request by jjerphan**
Partially fix https://github.com/mamba-org/mamba/issues/3393.

### CODE REVIEW

**Review by JohanMabille — COMMENTED** [review]
I think we should take the opportunity of these bug fixes to do some slight refactoring. Typically here the code is duplicated for no reeason, it should be factorize out.

**Comment by jjerphan** [comment]
Actually one needs to first fix [the regression observed](https://github.com/mamba-org/mamba/issues/3393#issuecomment-2405388129) between 1.x and 2.0.

**Comment by JohanMabille** [comment]
I don't see how the performance regression is preventing to factorize out code.

**Comment by jjerphan** [comment]
As discussed IRL, let's first merge this PR and let's tackle [this other issue](https://github.com/mamba-org/mamba/issues/3393#issuecomment-2405388129) in another one.

**Review by JohanMabille — APPROVED** [review]

**Pull request merged**
