### PR TITLE
add manually given .tar.bz2 / .conda packages to solver pool

### LINKED ISSUE #2291: Micromamba can't install local `.tar.bz2` package
See https://github.com/mamba-org/mamba/issues/2238#issuecomment-1430180999. Not sure if it's the same bug.

### PR DESCRIPTION
**Pull request by 0xbe7a**
Should hopefully close #2291

### CODE REVIEW

**Review by AntoinePrv — APPROVED** [review]
Thanks!

**Comment by Hind-M** [comment]
Hey @0xbe7a!
I just realized that the `install_local_package` test added in this PR is never run since it doesn't start with `test_`.
So I was wondering if you tested this locally to be sure I didn't miss anything, because when I tried (with `mamba/micromamba install file:///some_path/cph_test_data-0.0.1-0.tar.bz2`), the issue doesn't seem to be fixed.
Thanks!

**Comment by 0xbe7a** [comment]
I'm pretty sure i did test this locally, but the test should be fixed regardless

**Comment by Hind-M** [comment]
Yeah, I was just checking if this was working at some point... So far, I didn't manage to make it work for now.

**Pull request merged**
