### PR TITLE
Prepare 0.14.0 release

### PR DESCRIPTION
**Pull request by adriendelsalle**
Description
---

- [x] Update changelog

### CODE REVIEW

**Comment by marimeireles** [comment]
I have the `remove` option ready.
Just need to write some tests quickly. Can we fit it in?

**Comment by adriendelsalle** [comment]
hi @marimeireles sure, @wolfv also want to to add an extra fix in that one !

**Comment by marimeireles** [comment]
@wolfv you're gonna refactor it to reduce duplicated code?

**Comment by wolfv** [comment]
@marimeireles let's do it next time!

**Pull request merged**
