### PR TITLE
add stubs with pybind11-stubgen

### PR DESCRIPTION
**Pull request by dholth**
Move some declarations forward to banish C++ types from docstrings; generate stubs with `pybind11-stubgen libmambapy.bindings`

- [x] TODO, put the stubs where they belong

Unfortunately the following doesn't work

```
$ pybind11-stubgen libmambapy
Traceback (most recent call last):
  File "/home/dholth.linux/miniconda3/envs/mamba-dev/bin/pybind11-stubgen", line 8, in <module>
    sys.exit(main())
  File "/home/dholth.linux/miniconda3/envs/mamba-dev/lib/python3.10/site-packages/pybind11_stubgen/__init__.py", line 1109, in main
    _module.write()
  File "/home/dholth.linux/miniconda3/envs/mamba-dev/lib/python3.10/site-packages/pybind11_stubgen/__init__.py", line 971, in write
    init_pyi.write("\n".join(self.to_lines()))
  File "/home/dholth.linux/miniconda3/envs/mamba-dev/lib/python3.10/site-packages/pybind11_stubgen/__init__.py", line 936, in to_lines
    used_modules = sorted(self.get_involved_modules_names())
  File "/home/dholth.linux/miniconda3/envs/mamba-dev/lib/python3.10/site-packages/pybind11_stubgen/__init__.py", line 906, in get_involved_modules_names
    result |= f.get_involved_modules_names()
  File "/home/dholth.linux/miniconda3/envs/mamba-dev/lib/python3.10/site-packages/pybind11_stubgen/__init__.py", line 564, in get_involved_modules_names
    if self.is_valid_module(module_name):
  File "/home/dholth.linux/miniconda3/envs/mamba-dev/lib/python3.10/site-packages/pybind11_stubgen/__init__.py", line 294, in is_valid_module
    return importlib.import_module(module_name) is not None
  File "/home/dholth.linux/miniconda3/envs/mamba-dev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: generic_type: type "Channel" is already registered!
free(): invalid pointer
Aborted (core dumped)
```

### CODE REVIEW

**Comment by dholth** [comment]
Screen Shot 2022-10-03 at 1 10 47 PM

Looks good when the `.pyi` is copied to `libmambapy/__init__.pyi`

**Comment by dholth** [comment]
[ ] script to run pybind11-stubgen
[ ] pre-commit ignore generated file

**Comment by wolfv** [comment]
just fyi we use `pre-commit` which is pretty convenient for linting (just in case you ran `black` manually, `pre-commit` makes it a bit simpler).

**Comment by wolfv** [comment]
Awesome!

I was wondering about the two tick boxes, especially the script to generate these files automatically. Do we have to run something manually every time we change the `libmambapy` source code now? Should we at least have a linter check? So that people who change something get notified if they didn't run `pybind11-stubgen`?

**Comment by dholth** [comment]
This is what I did. I had to symlink the bindings underneath libmambapy (that's where they go? but they didn't get put there automatically in my dev environment?)

I ran `pybind11-stubgen libmambapy.bindings`

And then `mv stubs/libmambapy/bindings-stubs/__init__.pyi libmambapy/`

We know `libmambapy.bindings` is supposed to be exposed as just `libmambapy` but `pybind11-stubgen` does not know that.

```
~/prog/mamba/libmambapy$ ls -lh libmambapy
total 16K
-rw-rw-r-- 1 dholth dholth  258 Oct  3 16:14 __init__.py
drwxrwxr-x 2 dholth dholth 4.0K Oct  3 16:18 __pycache__
-rw-rw-r-- 1 dholth dholth   73 Oct  3 16:14 _version.py
-rw-rw-r-- 1 dholth dholth  126 Oct  3 16:14 _version.py.tmpl
lrwxrwxrwx 1 dholth dholth   44 Oct  3 16:29 bindings.cpython-310-aarch64-linux-gnu.so -> ../bindings.cpython-310-aarch64-linux-gnu.so
```

```
$ ls -R stubs/
stubs/:
libmambapy

stubs/libmambapy:
bindings-stubs

stubs/libmambapy/bindings-stubs:
__init__.pyi  setup.py
```

```
$ pybind11-stubgen --help
usage: pybind11-stubgen [-h] [-o OUTPUT_DIR]
                        [--root-module-suffix ROOT_MODULE_SUFFIX]
                        [--root_module_suffix ROOT_MODULE_SUFFIX_DEPRECATED]
                        [--no-setup-py] [--non-stop]
                        [--ignore-invalid {signature,defaultarg,all} [{signature,defaultarg,all} ...]]
                        [--skip-signature-downgrade] [--bare-numpy-ndarray]
                        [--log-level LOG_LEVEL]
                        MODULE_NAME [MODULE_NAME ...]

Generates stubs for specified modules

positional arguments:
  MODULE_NAME           modules names

options:
  -h, --help            show this help message and exit
  -o OUTPUT_DIR, --output-dir OUTPUT_DIR
                        the root directory for output stubs
  --root-module-suffix ROOT_MODULE_SUFFIX
                        optional suffix to disambiguate from the original
                        package
  --root_module_suffix ROOT_MODULE_SUFFIX_DEPRECATED
                        Deprecated. Use `--root-module-suffix`
  --no-setup-py
  --non-stop            Deprecated. Use `--ignore-invalid=all`
  --ignore-invalid {signature,defaultarg,all} [{signature,defaultarg,all} ...]
                        Ignore invalid specified python expressions in
                        docstrings
  --skip-signature-downgrade
                        Do not downgrade invalid function signatures to
                        func(*args, **kwargs)
  --bare-numpy-ndarray  Render `numpy.ndarray` without (non-standardized)
                        bracket-enclosed type and shape info
  --log-level LOG_LEVEL
                        Set output log level
```

**Pull request merged**
