### PR TITLE
Use separate artifact names per OS

### PR DESCRIPTION
**Pull request by jonashaag**
Also rename CI internal binary to reflect that it's internal.

### CODE REVIEW

**Comment by jonashaag** [comment]
@adriendelsalle you see to be the author of this test that's also failing on master, care to have a look?

**Comment by adriendelsalle** [comment]
Hi @jonashaag it's just a test to check the behavior of the `--no-py-pin` flag.
At this time it looks like the `python_abi` was installed for `python=3.9` thus downgraded when installing an old `setuptools`. Now it looks like the `python_abi` package is not installed anymore with `python=3.9` but still required by  `python=2.7`  then just linked and not unlinked.

But I don't see anything related to this PR: ?

**Comment by pavelzw** [comment]
Let's see which one gets merged first, this one or #1886 🤔. 

The loser needs to rebase :P

**Comment by jonashaag** [comment]
> But I don't see anything related to this PR: ?

That’s why I said it’s unrelated :)

**Comment by adriendelsalle** [comment]
oh sorry I read this a bit too fast ;). hope this help

**Comment by jonashaag** [comment]
Thanks, see #1889 

@pavelzw can you incorporate this into #1888?

**Pull request closed without merging**
