### PR TITLE
Update micromamba installation docs for Windows

### PR DESCRIPTION
**Pull request by Tiksagol**
No need to use 7zip as Windows 10 contains tar.exe (and the former might not be installed).

### CODE REVIEW

**Comment by wolfv** [comment]
@Tiksagol does it really? I haven't really seen that in the wild (except on CI systems that is indeed the case).

I think we're working more towards putting the non-compressed binary somewhere so that installation becomes even simpler.

**Comment by jonashaag** [comment]
To that end, want to deploy this script? https://github.com/mamba-org/mamba/issues/2164#issuecomment-1359564081

**Comment by Tiksagol** [comment]
> @Tiksagol does it really? I haven't really seen that in the wild (except on CI systems that is indeed the case).
> 
> I think we're working more towards putting the non-compressed binary somewhere so that installation becomes even simpler.

@wolfv - yes, works fine on Windows 10

**Comment by jonashaag** [comment]
I think it ships bsdtar. You can see usage in the provision-with-micromamba code, which is compatible with bare bones Windows systems.

**Comment by wolfv** [comment]
This article is from April 22 https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows

So I guess it's true! I'm fine with changing it to curl + tar in that case and keep the old one as reference for older systems.

**Comment by Tiksagol** [comment]
> I think it ships bsdtar. You can see usage in the provision-with-micromamba code, which is compatible with bare bones Windows systems.

@jonashaag - right:

`C:\Users\me>tar --version
bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp bz2lib/1.0.6`

**Comment by wolfv** [comment]
Hmmmmm, can you double check this for me? 

On a windows server installation I can access, teh windows shipped `tar` doesn't have `bzip2` support (see screenshot).

Screenshot 2023-01-22 at 01 13 07

**Comment by Tiksagol** [comment]
> Hmmmmm, can you double check this for me?
> 
> On a windows server installation I can access, teh windows shipped `tar` doesn't have `bzip2` support (see screenshot).
> 
> Screenshot 2023-01-22 at 01 13 07

Seems like it has, as in my laptop it works and returned the same output (its end seems to be removed from your screenshot) - 
```
c:\Windows\System32>.\tar.exe --version
bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp **bz2lib/1.0.6**
```

**Pull request merged**
