### PR TITLE
Fix test_python_pinning

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by pavelzw** [comment]
I ran the test in my CI with some debug print statements:

```py
link_packages = {'setuptools', 'wheel', 'python', 'python_abi', 'libffi', 'zlib', 'pip', 'libstdcxx-ng', 'openssl', 'certifi'}
unlink_packages = {'setuptools', 'wheel', 'python', 'libffi', 'pip', 'openssl'}
```

**Comment by pavelzw** [comment]
And in the Windows case:

```py
link_packages = {'wheel', 'pip', 'python', 'certifi', 'wincertstore', 'setuptools'}
```

**Comment by jonashaag** [comment]
Jesus

**Comment by pavelzw** [comment]
<details>
<summary>It didn't print out the `unlink_packages` because it failed before... Here is the complete `res`</summary>

```py
{
    "actions": {
        "FETCH": [
            {
                "build": "he025d50_2",
                "build_number": 2,
                "build_string": "he025d50_2",
                "channel": "https://conda.anaconda.org/conda-forge/win-64",
                "constrains": ["python_abi * *_cp35m"],
                "depends": ["pip", "vc >=14,<15.0a0"],
                "fn": "python-3.5.5-he025d50_2.tar.bz2",
                "license": "PSF",
                "md5": "ca6d8bdc57ac239e01050d98a499bc8c",
                "name": "python",
                "sha256": "a02c22e70ddcfc745e729f6880c662c4feb71f61858948c8d9530835b5e4c332",
                "size": 19475230,
                "subdir": "win-64",
                "timestamp": 1532397437,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/win-64/python-3.5.5-he025d50_2.tar.bz2",
                "version": "3.5.5",
            },
            {
                "build": "py35_1002",
                "build_number": 1002,
                "build_string": "py35_1002",
                "channel": "https://conda.anaconda.org/conda-forge/win-64",
                "constrains": ["python_abi * *_cp35m"],
                "depends": ["python >=3.5,<3.6.0a0"],
                "fn": "wincertstore-0.2-py35_1002.tar.bz2",
                "license": "PSF 2",
                "md5": "5666563c6602431859e57caa1871012c",
                "name": "wincertstore",
                "sha256": "f04df25b0179525a0b74d5fb54009e90b43d5f7295c9e1e83f1bd603aff7d372",
                "size": 13128,
                "subdir": "win-64",
                "timestamp": 1537716771,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/win-64/wincertstore-0.2-py35_1002.tar.bz2",
                "version": "0.2",
            },
            {
                "build": "py35_1001",
                "build_number": 1001,
                "build_string": "py35_1001",
                "channel": "https://conda.anaconda.org/conda-forge/win-64",
                "constrains": ["python_abi * *_cp35m"],
                "depends": ["python >=3.5,<3.6.0a0"],
                "fn": "certifi-2018.8.24-py35_1001.tar.bz2",
                "license": "ISC",
                "md5": "252d055a8f6f032834e55594cb75a3ff",
                "name": "certifi",
                "sha256": "54a0b07821256ebeab58ee7a4d8ec03a59bd929f7959571e26af91997ac1bb37",
                "size": 141961,
                "subdir": "win-64",
                "timestamp": 1537666495,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/win-64/certifi-2018.8.24-py35_1001.tar.bz2",
                "version": "2018.8.24",
            },
            {
                "build": "py35_0",
                "build_number": 0,
                "build_string": "py35_0",
                "channel": "https://conda.anaconda.org/conda-forge/win-64",
                "constrains": ["python_abi * *_cp35m"],
                "depends": ["certifi", "wincertstore", "python 3.5*"],
                "fn": "setuptools-28.4.0-py35_0.tar.bz2",
                "license": "MIT",
                "md5": "9b46ce94aab064e2a767440fb5d76dc1",
                "name": "setuptools",
                "sha256": "fcc669e28037cd709f2f070158f439ff63c8574d929c3ccfc2cc119e99364d61",
                "size": 549089,
                "subdir": "win-64",
                "timestamp": 0,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/win-64/setuptools-28.4.0-py35_0.tar.bz2",
                "version": "28.4.0",
            },
            {
                "build": "pyhd8ed1ab_0",
                "build_number": 0,
                "build_string": "pyhd8ed1ab_0",
                "channel": "https://conda.anaconda.org/conda-forge/noarch",
                "constrains": None,
                "depends": ["setuptools", "wheel", "python >=3"],
                "fn": "pip-20.3.4-pyhd8ed1ab_0.tar.bz2",
                "license": "MIT",
                "md5": "a9f505dda2243420dc8e8681cda95be8",
                "name": "pip",
                "sha256": "b8c5ad9fe49a5396ca2cec1f7024b4d7ee30d8ba12595653cfc83bf072617384",
                "size": 1138591,
                "subdir": "noarch",
                "timestamp": 1611414382,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/noarch/pip-20.3.4-pyhd8ed1ab_0.tar.bz2",
                "version": "20.3.4",
            },
        ],
        "LINK": [
            {
                "build": "he025d50_2",
                "build_number": 2,
                "build_string": "he025d50_2",
                "channel": "https://conda.anaconda.org/conda-forge/win-64",
                "constrains": ["python_abi * *_cp35m"],
                "depends": ["pip", "vc >=14,<15.0a0"],
                "fn": "python-3.5.5-he025d50_2.tar.bz2",
                "license": "PSF",
                "md5": "ca6d8bdc57ac239e01050d98a499bc8c",
                "name": "python",
                "sha256": "a02c22e70ddcfc745e729f6880c662c4feb71f61858948c8d9530835b5e4c332",
                "size": 19475230,
                "subdir": "win-64",
                "timestamp": 1532397437,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/win-64/python-3.5.5-he025d50_2.tar.bz2",
                "version": "3.5.5",
            },
            {
                "build": "py35_1002",
                "build_number": 1002,
                "build_string": "py35_1002",
                "channel": "https://conda.anaconda.org/conda-forge/win-64",
                "constrains": ["python_abi * *_cp35m"],
                "depends": ["python >=3.5,<3.6.0a0"],
                "fn": "wincertstore-0.2-py35_1002.tar.bz2",
                "license": "PSF 2",
                "md5": "5666563c6602431859e57caa1871012c",
                "name": "wincertstore",
                "sha256": "f04df25b0179525a0b74d5fb54009e90b43d5f7295c9e1e83f1bd603aff7d372",
                "size": 13128,
                "subdir": "win-64",
                "timestamp": 1537716771,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/win-64/wincertstore-0.2-py35_1002.tar.bz2",
                "version": "0.2",
            },
            {
                "build": "py35_1001",
                "build_number": 1001,
                "build_string": "py35_1001",
                "channel": "https://conda.anaconda.org/conda-forge/win-64",
                "constrains": ["python_abi * *_cp35m"],
                "depends": ["python >=3.5,<3.6.0a0"],
                "fn": "certifi-2018.8.24-py35_1001.tar.bz2",
                "license": "ISC",
                "md5": "252d055a8f6f032834e55594cb75a3ff",
                "name": "certifi",
                "sha256": "54a0b07821256ebeab58ee7a4d8ec03a59bd929f7959571e26af91997ac1bb37",
                "size": 141961,
                "subdir": "win-64",
                "timestamp": 1537666495,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/win-64/certifi-2018.8.24-py35_1001.tar.bz2",
                "version": "2018.8.24",
            },
            {
                "build": "py35_0",
                "build_number": 0,
                "build_string": "py35_0",
                "channel": "https://conda.anaconda.org/conda-forge/win-64",
                "constrains": ["python_abi * *_cp35m"],
                "depends": ["certifi", "wincertstore", "python 3.5*"],
                "fn": "setuptools-28.4.0-py35_0.tar.bz2",
                "license": "MIT",
                "md5": "9b46ce94aab064e2a767440fb5d76dc1",
                "name": "setuptools",
                "sha256": "fcc669e28037cd709f2f070158f439ff63c8574d929c3ccfc2cc119e99364d61",
                "size": 549089,
                "subdir": "win-64",
                "timestamp": 0,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/win-64/setuptools-28.4.0-py35_0.tar.bz2",
                "version": "28.4.0",
            },
            {
                "build": "pyhd8ed1ab_0",
                "build_number": 0,
                "build_string": "pyhd8ed1ab_0",
                "channel": "https://conda.anaconda.org/conda-forge/noarch",
                "constrains": None,
                "depends": ["python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4"],
                "fn": "wheel-0.37.1-pyhd8ed1ab_0.tar.bz2",
                "license": "MIT",
                "md5": "1ca02aaf78d9c70d9a81a3bed5752022",
                "name": "wheel",
                "sha256": "aede66e6370f3b936164a703e48362f9080d7162234058fb2ee63cc84d528afc",
                "size": 32022,
                "subdir": "noarch",
                "timestamp": 1640197340,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/noarch/wheel-0.37.1-pyhd8ed1ab_0.tar.bz2",
                "version": "0.37.1",
            },
            {
                "build": "pyhd8ed1ab_0",
                "build_number": 0,
                "build_string": "pyhd8ed1ab_0",
                "channel": "https://conda.anaconda.org/conda-forge/noarch",
                "constrains": None,
                "depends": ["setuptools", "wheel", "python >=3"],
                "fn": "pip-20.3.4-pyhd8ed1ab_0.tar.bz2",
                "license": "MIT",
                "md5": "a9f505dda2243420dc8e8681cda95be8",
                "name": "pip",
                "sha256": "b8c5ad9fe49a5396ca2cec1f7024b4d7ee30d8ba12595653cfc83bf072617384",
                "size": 1138591,
                "subdir": "noarch",
                "timestamp": 1611414382,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/noarch/pip-20.3.4-pyhd8ed1ab_0.tar.bz2",
                "version": "20.3.4",
            },
        ],
        "PREFIX": "C:\\Users\\runneradmin\\tmprootA7Q3N43ULP\\envs\\Z50XB52D37",
        "UNLINK": [
            {
                "build": "hcf16a7b_0_cpython",
                "build_number": 0,
                "build_string": "hcf16a7b_0_cpython",
                "channel": "conda-forge",
                "constrains": ["python_abi 3.9.* *_cp39"],
                "depends": [
                    "bzip2 >=1.0.8,<2.0a0",
                    "libffi >=3.4.2,<3.5.0a0",
                    "libzlib >=1.2.11,<1.3.0a0",
                    "openssl >=3.0.3,<4.0a0",
                    "sqlite >=3.38.5,<4.0a0",
                    "tk >=8.6.12,<8.7.0a0",
                    "tzdata",
                    "vc >=14.1,<15",
                    "vs2015_runtime >=14.16.27033",
                    "xz >=5.2.5,<5.3.0a0",
                    "pip",
                ],
                "fn": "python-3.9.13-hcf16a7b_0_cpython.tar.bz2",
                "license": "",
                "md5": "6017838044b4b984cffd2600d31a11de",
                "name": "python",
                "sha256": "63e7fb11f273bd4481bebcfec301b54f6c8df69073914b8f05e615ad8b56d733",
                "size": 18734502,
                "subdir": "win-64",
                "timestamp": 0,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/win-64/python-3.9.13-hcf16a7b_0_cpython.tar.bz2",
                "version": "3.9.13",
            },
            {
                "build": "pyhd8ed1ab_1",
                "build_number": 1,
                "build_string": "pyhd8ed1ab_1",
                "channel": "conda-forge",
                "constrains": None,
                "depends": ["python >=3.8"],
                "fn": "setuptools-65.3.0-pyhd8ed1ab_1.tar.bz2",
                "license": "",
                "md5": "a64c8af7be7a6348c1d9e530f88fa4da",
                "name": "setuptools",
                "sha256": "54d2d1480c6f01a9b0a368276b95a71062eb3995183b10de04ec26d5e2571fcd",
                "size": 800875,
                "subdir": "noarch",
                "timestamp": 0,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/noarch/setuptools-65.3.0-pyhd8ed1ab_1.tar.bz2",
                "version": "65.3.0",
            },
            {
                "build": "pyhd8ed1ab_0",
                "build_number": 0,
                "build_string": "pyhd8ed1ab_0",
                "channel": "conda-forge",
                "constrains": None,
                "depends": ["python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4"],
                "fn": "wheel-0.37.1-pyhd8ed1ab_0.tar.bz2",
                "license": "",
                "md5": "1ca02aaf78d9c70d9a81a3bed5752022",
                "name": "wheel",
                "sha256": "aede66e6370f3b936164a703e48362f9080d7162234058fb2ee63cc84d528afc",
                "size": 32022,
                "subdir": "noarch",
                "timestamp": 0,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/noarch/wheel-0.37.1-pyhd8ed1ab_0.tar.bz2",
                "version": "0.37.1",
            },
            {
                "build": "pyhd8ed1ab_0",
                "build_number": 0,
                "build_string": "pyhd8ed1ab_0",
                "channel": "conda-forge",
                "constrains": None,
                "depends": ["python >=3.7", "setuptools", "wheel"],
                "fn": "pip-22.2.2-pyhd8ed1ab_0.tar.bz2",
                "license": "",
                "md5": "0b43abe4d3ee93e82742d37def53a836",
                "name": "pip",
                "sha256": "507ae896a2f9ccc7bbedc2f7fd10dc2ac666575769b55b5e94ca44b86db193e0",
                "size": 1566504,
                "subdir": "noarch",
                "timestamp": 0,
                "track_features": "",
                "url": "https://conda.anaconda.org/conda-forge/noarch/pip-22.2.2-pyhd8ed1ab_0.tar.bz2",
                "version": "22.2.2",
            },
        ],
    },
    "dry_run": False,
    "prefix": "C:\\Users\\runneradmin\\tmprootA7Q3N43ULP\\envs\\Z50XB52D37",
    "success": True,
}
```

</details>

**Comment by jonashaag** [comment]
@adriendelsalle do you think this patch makes sense? Is the test still useful?

**Comment by JohanMabille** [comment]
I'm not 100% sure the test is still useful (but I guess), so I think it is better to fix it now and see later if we can remove it than removing it now and realize later it was still useful ;) I will merge the PR when the CI is green, thanks for the fix!

**Comment by adriendelsalle** [comment]
Yep I think it would worth to keep a test about python pinning (and also pinning removal)

**Pull request merged**
