### PR TITLE
add `context.register_envs` to control whether environments are registered to `environments.txt` or not

### LINKED ISSUE #2783: Add mechanism to control wether global files `~/.conda/environments.txt` are written to or not
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

NA

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

micromamba notes down all environments in the ~/.conda/environments.txt global file. 

Some people that use micromamba more programatically do not like that it writes to a global file. We could add a boolean variable to the configuration that controls this behavior and prevents micromamba from writing to this file.

### mamba info / micromamba info

_No response_

### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

_No response_

### PR DESCRIPTION
**Pull request by jaimergp**
Closes #2783 

xref https://github.com/conda/conda/pull/12924
xref https://github.com/conda/constructor/pull/716

### CODE REVIEW

**Review by JohanMabille — APPROVED** [review]

**Comment by JohanMabille** [comment]
Thanks!

**Comment by jonashaag** [comment]
Is there any good way to write a test for this?

**Comment by wolfv** [comment]
I love this but we need to wire it up, right? 
It should probably be accessible from 

- python
- CLI
- Environment variable
- Config

cc @JohanMabille

**Comment by jaimergp** [comment]
> Is there any good way to write a test for this?

This is what `conda` has: https://github.com/conda/conda/blob/adcf8ef6f268cf8f77cf2b433d1ccf56fad94bdb/tests/core/test_envs_manager.py#L32

And in constructor: https://github.com/conda/constructor/blob/cf0f466bc72c1b3b2d2bf435046b8686c335a52c/tests/test_examples.py#L449

**Pull request merged**
