### PR TITLE
maint: Update clang-format to v19

### PR DESCRIPTION
**Pull request by mathbunnyru**
Possible options (I didn't change any): https://clang.llvm.org/docs/ClangFormatStyleOptions.html

### CODE REVIEW

**Review by jjerphan — COMMENTED** [review]
LGTM if and only if the merge commit of this PR has its diff ignored since it bring no semantic changes.

For more information, see:
 - https://github.com/orgs/community/discussions/5033
 - https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/

**Comment by Hind-M** [comment]
To have a consistent history and since the formatting commits were always explicit, I think we should actually just leave the files diff as is (not ignored) so that we know that a change was made regarding the format.

**Comment by Hind-M** [comment]
@klaim Any objections on the format result? (We may change the options if any).

**Comment by Klaim** [comment]
> @Klaim Any objections on the format result? (We may change the options if any).

Looks tolerable to me. 👍🏽 

To be completely clear, there are things I'm not a fan of but that I can totally live with:
- having the return type on a second line when using the `auto ... ->` function signature syntax is nice, but I would prefer the short signatures to not have that second line, as it seems not necessary (only on short signatures) - but I can live with systematic return type separated;
- My preferred style of lambda expression is to have the `{` on the same line as the signature (like some post-java languages?), so that the content of the body looks like it's part of the expression hosting the lambda expression (`func(a, b, []{ ...`), and it avoids having too many lines in short lambdas, and also that makes the lambda expressions standout stylistically when you use a different style for most C++ expressions (`{` and `}` always on a new line for example, to mark a scope clearly); here we get a new line per `{` systematically and the signature is kind of disconnected visually - but it's really minor and I can also totally live with it;

Also I don't know the limitations of clang-format regarding these minor points, maybe it's just not possible to have the exact style I prefer. Probably not worth our time if everybody can live with this style.

So I think we're good to go. 👍🏽

**Comment by jjerphan** [comment]
I let anyone of you merge this PR.

**Pull request merged**
