### PR TITLE
Add support for use_only_tar_bz2

### PR DESCRIPTION
**Pull request by tl-hbk**
Change for https://github.com/mamba-org/mamba/issues/666.  Will need a new release of libsolv but I'd like for the windows regex fix to be merged before requesting that.

EDIT: Will need to rerun tests after new libsolv is available with the new flag.  Tested this locally already with a locally built copy of libsolv and works as expected.

### CODE REVIEW

**Comment by wolfv** [comment]
@tl-hbk thanks a lot for these changes! Sooner or later it would be cool to add this feature to micromamba, too. Maybe @adriendelsalle can comment on what changes to the `rc` file reading and CLI flags are necessary.

**Comment by adriendelsalle** [comment]
Sure, will do soon-ish!

**Comment by wolfv** [comment]
We've added the two patches from libsolv master to the libsolv feedstock (that means the build with _1 should have the new functionality).

**Comment by tl-hbk** [comment]
Awesome thanks for doing that

**Pull request merged**
