### PR TITLE
Don't create a prefix which is missing conda-meta

### PR DESCRIPTION
**Pull request by maresb**
To illustrate the problem, run the following:

```bash
docker run --rm -it mambaorg/micromamba:1.1.0
unset MAMBA_ROOT_PREFIX
micromamba shell init
micromamba shell init
```

The first `shell init` command creates a root prefix `~/micromamba` which contains the single file `~/micromamba/etc/profile.d/micromamba.sh`. The second `shell init` validates the root prefix by checking for `~/micromamba/conda-meta`, which is missing, causing the following error:

```
critical libmamba Could not use default 'root_prefix': /home/mambauser/micromamba: Directory exists, is not empty and not a conda prefix.
```

Workaround with Bash:
```bash
docker run --rm -it mambaorg/micromamba:1.1.0
unset MAMBA_ROOT_PREFIX
micromamba shell init
mkdir -p ~/micromamba/conda-meta
micromamba shell init
```

This PR which I'm submitting is untested, but it should at least convey what I believe the fix should be.

### CODE REVIEW

**Comment by jonashaag** [comment]
Thanks! Do you have time to add a test?

**Comment by jonashaag** [comment]
I think this is the same issue as https://github.com/mamba-org/mamba/issues/1895#issuecomment-1242808731 which I believed to be fixed but it’s not

**Comment by maresb** [comment]
I was having some trouble getting pytest to run in my local environment. Thus I haven't yet tested the test. :smile:

**Comment by maresb** [comment]
Thanks a lot for cleaning this up!!!

**Review by wolfv — APPROVED** [review]

**Pull request merged**
