### PR TITLE
Fix CI by pointing to updated feedstock

### PR DESCRIPTION
**Pull request by AntoinePrv**
Pointing the micromamba static feedstock to https://github.com/conda-forge/micromamba-feedstock/pull/97.

### CODE REVIEW

**Comment by wolfv** [comment]
@AntoinePrv we merged a PR on the micromamba feedstock yesterday that also adds the `spdlog` pin there

**Comment by AntoinePrv** [comment]
@wolf, I saw, this does more

**Comment by AntoinePrv** [comment]
Well, it improves one of the static build, that's something :sweat_smile:

**Comment by AntoinePrv** [comment]
Hmm OK, the patching of the url is broken on linux if I remove `libmamba.patch` from the repo

**Comment by jonashaag** [comment]
cc @pavelzw

**Comment by wolfv** [comment]
So there was a bug in the tests, and the recent python 3.11 release made it appear... let's see if this works now 🪠

**Comment by AntoinePrv** [comment]
Seems like it solved the umamba test on Ubuntu. I hope with this formatting it will be good.

@wolfv What's the plan for merging (as the feedstock for used for static test point to a fork)? What about?
- 1. Merge this pointing `AntoinePrv/micromamba-feedstock`,
- 2. Release (bugfix?)
- 3. Merge `AntoinePrv/micromamba-feedstock@spdlog`
- 4. Point back to `conda-forge/micromamba-feedstock`

**Comment by wolfv** [comment]
I think it's better to not release another micromamba release now. I am happy to keep pointing to your feedstock fork for the moment (or we can fork into `mamba-org` if you want).

**Comment by wolfv** [comment]
e.g. the micromamba releases seem to break `brew install micromamba` and stuff like that: https://github.com/mamba-org/mamba/issues/2057

**Comment by AntoinePrv** [comment]
Ok, then let's keep pointing as it is. I'll open issues and PR to keep track of things.

**Pull request merged**
