### PR TITLE
Dead code?

### PR DESCRIPTION
**Pull request by marimeireles**

### CODE REVIEW

**Comment by marimeireles** [comment]
Ok, this is a mistake. I don't think any of these should be removed.
I'll just add a little test for `print_context_only` and add documentation for the others.

**Comment by wolfv** [comment]
I don't think we need to document these as they are really only used in tests -- at least the print-context-only.

**Comment by JohanMabille** [comment]
A few comments in the code won't hurt ;)

**Comment by wolfv** [comment]
yep, 100% agree. need to get better at this :)

**Comment by marimeireles** [comment]
Seems good!

**Comment by marimeireles** [comment]
But is the `--debug` flag really only used in the tests?
If it is then I think `print_context_only` is dead code cause it's not used in the tests, it's only use it's in [here](https://github.com/mamba-org/mamba/blob/b3aef48677b08e540e7ec4b08c03d6099ff48969/libmamba/include/mamba/api/configuration.hpp#L24-L37).

**Pull request closed without merging**
