### PR TITLE
blacklist lower prio packages

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
Merging this for now, until we have a way to do this in libsolv directly

**Comment by adriendelsalle** [comment]
I'm not sure adding this in `MSolver::add_jobs` is the right place, it may be called multiple times.
Is it also possible to add tests, especially when it modifies the solver behavior?

**Comment by wolfv** [comment]
It's added in Solver::solve.

For tests, I think this specific feature is covered in libsolv.

**Comment by adriendelsalle** [comment]
> It's added in Solver::solve.

ah yes sorry the code was collapsed and I got confused

> For tests, I think this specific feature is covered in libsolv.

the unit test about blacklisting is tested in libsolv but the usage we have in `mamba` is not

**Pull request merged**
