### PR TITLE
A quick fix for the issue of update env with --prune flag

### PR DESCRIPTION
**Pull request by ZHG2017**
This is a quickfix for the issue #3174 

Added install request construction for the update process

Added condition test to avoid conflict for removing and updating the same package at the same time

Added unit test to validate the fix

### CODE REVIEW

**Comment by Hind-M** [comment]
Thanks for the PR.
Can you only include in this one the relevant files for the bug fix? The documentation related files should be in another PR (I think reopening #3217 will do).
For the `Linters` failure in the CI, running `pre-commit run --all` in the mamba source folder locally before committing should fix it.

**Comment by ZHG2017** [comment]
> Thanks for the PR. Can you only include in this one the relevant files for the bug fix? The documentation related files should be in another PR (I think reopening #3217 will do). For the `Linters` failure in the CI, running `pre-commit run --all` in the mamba source folder locally before committing should fix it (it will most likely modify the non-compliant files to follow the linting rules (defined [here](https://github.com/mamba-org/mamba/blob/main/.pre-commit-config.yaml)), so you should add them and commit them).

Hi @Hind-M , Thank you for the suggestion. Let me figure out how to use hte `linter` then. And I think I will create a new branch as well as a new PR for the documentation since I messed up some commits.

**Comment by Hind-M** [comment]
What was the reason the bug is happening, the corresponding [test](https://github.com/mamba-org/mamba/blob/main/micromamba/tests/test_env.py#L159-L175) is supposed to check the `--prune` flag's behavior...
Can you add a test reproducing the issue and showing that this PR patch is fixing it?

**Comment by ZHG2017** [comment]
> Thanks for the PR. Can you only include in this one the relevant files for the bug fix? The documentation related files should be in another PR (I think reopening #3217 will do). For the `Linters` failure in the CI, running `pre-commit run --all` in the mamba source folder locally before committing should fix it (it will most likely modify the non-compliant files to follow the linting rules (defined [here](https://github.com/mamba-org/mamba/blob/main/.pre-commit-config.yaml)), so you should add them and commit them).

Hi, I have tried to use the `pre-commit` but did not find it any where, I checked in the folder `.git/hooks/` but there is nothing related to this CI check.  I wonder if this CI check only happens on the server

**Comment by ZHG2017** [comment]
> What was the reason the bug is happening, the corresponding [test](https://github.com/mamba-org/mamba/blob/main/micromamba/tests/test_env.py#L159-L175) is supposed to check the `--prune` flag's behavior... Can you add a test reproducing the issue and showing that this PR patch is fixing it?

Yes, I have just realized that I did not add any unit test to validate my fix, actually I only manually typed some CLI command to verify if the fix works for the concerned issue.
The issue happens because the update inside the mamba will check if any package is previously installed in the target environment, if so, the update process will mark it as remove but just after that the internal process will mark the same package to be updated which is seemingly a conflict. Meanwhile, the most recent version of mamba will just ignore any installed package for a given environment file and will not install any package if it is missing in a given environment file.

**Comment by Hind-M** [comment]
> > Thanks for the PR. Can you only include in this one the relevant files for the bug fix? The documentation related files should be in another PR (I think reopening #3217 will do). For the `Linters` failure in the CI, running `pre-commit run --all` in the mamba source folder locally before committing should fix it (it will most likely modify the non-compliant files to follow the linting rules (defined [here](https://github.com/mamba-org/mamba/blob/main/.pre-commit-config.yaml)), so you should add them and commit them).
> 
> Hi, I have tried to use the `pre-commit` but did not find it any where, I checked in the folder `.git/hooks/` but there is nothing related to this CI check. I wonder if this CI check only happens on the server

So if you're working within an environment created from the [environment-dev.yml](https://github.com/mamba-org/mamba/blob/main/dev/environment-dev.yml#L48) file, `pre-commit` should be already installed (you can check using `mamba list` if `mamba` is the package manager you're using).
Otherwise, you can install it (`mamba install pre-commit -c conda-forge`).

Then, you only need to run `pre-commit run --all` in your git root folder. If you run `git status` afterwards, you will see the modified files that you'll need to commit.

**Comment by ZHG2017** [comment]
> > > Thanks for the PR. Can you only include in this one the relevant files for the bug fix? The documentation related files should be in another PR (I think reopening #3217 will do). For the `Linters` failure in the CI, running `pre-commit run --all` in the mamba source folder locally before committing should fix it (it will most likely modify the non-compliant files to follow the linting rules (defined [here](https://github.com/mamba-org/mamba/blob/main/.pre-commit-config.yaml)), so you should add them and commit them).
> > 
> > 
> > Hi, I have tried to use the `pre-commit` but did not find it any where, I checked in the folder `.git/hooks/` but there is nothing related to this CI check. I wonder if this CI check only happens on the server
> 
> So if you're working within an environment created from the [environment-dev.yml](https://github.com/mamba-org/mamba/blob/main/dev/environment-dev.yml#L48) file, `pre-commit` should be already installed (you can check using `mamba list` if `mamba` is the package manager you're using). Otherwise, you can install it: `mamba install pre-commit -c conda-forge`
> 
> Then, you only need to run `pre-commit run --all` in your git root folder. If you run `git status` afterwards, you will see the modified files that you'll need to commit.

Hi, I have used the  `pre-commit run --all` to format the code of mamba meanwhile I am still working on how to setup a unit test to prove my modification.

**Comment by Hind-M** [comment]
There is `test_classic_spec`  in `test_update.py` failing [here](https://github.com/mamba-org/mamba/actions/runs/8434394421/job/23098036714?pr=3243). The modifications should have broken it.
This is due to the solution actions in transaction [not empty](https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/transaction.cpp#L828-L831)  and so the ["message" key](https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/transaction.cpp#L374-L378) is missing.

**Comment by ZHG2017** [comment]
> There is `test_classic_spec` in `test_update.py` failing [here](https://github.com/mamba-org/mamba/actions/runs/8434394421/job/23098036714?pr=3243). The modifications should have broken it. This is due to the solution actions in transaction [not empty](https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/transaction.cpp#L828-L831) and so the ["message" key](https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/transaction.cpp#L374-L378) is missing.

Well, I have no idea how to fix this, I tried once using the built executable with my modification and the one built without my modification manually, and I saw no difference for the output. I don't know what can I do to pass this test.

**Pull request closed without merging**
