### PR TITLE
Avoid using /tmp

### PR DESCRIPTION
**Pull request by johnhany97**
Attempts to fix https://github.com/mamba-org/mamba/issues/2418

I realised that we already attempt to rename, and if that failed, we attempt to copy then delete the file. However, this seems to still cause `Invalid cross-device link error`.

My proposal is to just avoid storing the temporary file in `/tmp`, and instead use the same cache dir we already use for writing the .json files.

### CODE REVIEW

**Comment by johnhany97** [comment]
Given the nondeterministic nature of the issue at hand, i'm likely to try and get a patched version of mamba with this change and run it for a bit on our internal development infra to see if the issue still pops up or not. I won't be able to do so for at least a week though.

**Comment by jonashaag** [comment]
Not sure if this fixes anything, see discussion here: https://github.com/mamba-org/mamba/issues/2239#issuecomment-1400016398

**Comment by johnhany97** [comment]
I guess the alternative then would be to read the file and write it again ourselves to the new location? Happy to repurpose the code to do so.

**Comment by johnhany97** [comment]
I guess the alternative then would be to read the file and write it again ourselves to the new location? Happy to repurpose the code to do so.

**Comment by johnhany97** [comment]
I guess the alternative then would be to read the file and write it again ourselves to the new location? Happy to repurpose the code to do so.

**Review by wolfv — APPROVED** [review]

**Pull request merged**
